### ISSUE TITLE
CocoaPods?

### ISSUE THREAD

**Issue by andriitishchenko** [rob-nash/CollapsableTable#4]
hi! Could you add CocoaPods please?

**Comment by rob-nash** [comment]
I am not a fan of CocoaPods. This library is Carthage compliant. Carthage is my preferred dependency manager. Sorry.

**Comment by lfarah** [comment]
Hey @rob-nash, there are a lot of people who are already using CocoaPods on their projects and having both CocoaPods and Carthage in a project isn't optimal. I understand your preference over **Carthage**, but I'd be cool for *CollapsableOptions* to also support **CocoaPods** for the people who use it.

It's really simple to make *CollapsibleOptions* compatible. I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).
