### ISSUE TITLE
Cannot close section 

### ISSUE THREAD

**Issue by huxley27** [rob-nash/CollapsableTable#6]
Hi Sir, Thank you for your great library :) 
I noticed something that when the section 1 has more than 10 items or more then I scrolled the rows up and say the only visible rows are 3 - 15 then I tapped the section, It doesn't close. as per checking on your code I saw it here

```
RRNCollapsableTableViewController....

line 174 

for (NSInteger i = 0; i < [tableView numberOfSections]; i++) {
        **CGRect rect = [tableView rectForHeaderInSection:i];**
        if (CGRectContainsPoint(rect, point)) {
            return @(i);
        }
    }
```

it doesn't consider the content offset of the tableview. is this one of your roadmaps to fix this sir? 
Thank you! :)

**Comment by rob-nash** [comment]
Hi. Thanks for letting me know. I will fix this tomorrow.

**Comment by rob-nash** [comment]
I have included this as a feature. To avoid the collapse animation scrolling offscreen, the animation sequence begins by scrolling the content offset up to the first row in the selected section. Once completed to collapse animation begins.

https://github.com/rob-nash/CollapsableTable/releases/tag/1.1.0
