### ISSUE TITLE
Issue with separators during animation

### ISSUE THREAD

**Issue by arnaudWasappli** [rob-nash/CollapsableTable#9]
![separator](https://user-images.githubusercontent.com/7737273/27542027-fd26fc3e-5a53-11e7-9c7d-338a7ed8bb2b.gif)

**Comment by rob-nash** [comment]
Apple engineers produced this, which does the same thing. I'm not going to spend too much time trying to figure out a workaround.

https://developer.apple.com/library/content/samplecode/TableViewUpdates/Introduction/Intro.html

Feel free to have a go yourself.

**Comment by rob-nash** [comment]
Figured it out. 

First, remove cell separators.

```swift
tableView.separatorStyle = .none
```

Then add your own separator by adding a view to your UITableViewCell subclass. Maybe 1 point in height, positioned at the bottom of your cell.
